#production

FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @angular/cli

COPY . .

RUN ng build test-component

RUN ng build --configuration=production

FROM nginx:latest

COPY --from=build app/dist/app /usr/share/nginx/html

EXPOSE 80